#docker system prune -a --volumes #cmd to remove everything

services:
  amplizard_platform_production:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "9090:9090"
    depends_on:
      - redis
      - postgres
    env_file: ".env"  # Uncomment to use environment variables from the .env file
    environment:
      - NODE_ENV=production
      # Uncomment the following lines if you want to provide env vars directly
      # - host=0.0.0.0
      # - port=9090
      # - POSTGRES_HOST=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_DB=agentZ
      # - POSTGRES_PORT=5432
      # - POSTGRES_PASSWORD=postgres
      # - redis_url=redis://redis:6379
    networks:
      - amplizard_net

    restart: always
    command: npm run start

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - /var/amplizard/redis_data:/data
    networks:
      - amplizard_net
    restart: always

  postgres:
    container_name: amplizard_db
    image: postgres:latest
    env_file: ".env"  # Uncomment to use environment variables from the .env file
    # Uncomment the following lines if you want to provide env vars directly
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=amplizard
    #   - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/amplizard/postgres_data:/var/lib/postgresql/data
    networks:
      - amplizard_net
    restart: always

networks:
  amplizard_net:
    driver: bridge
