services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    env_file: ".env" #comment out this line if you want to provide env vars directly, and use the env vars given below.
    #environment:
      #- POSTGRES_USER=postgres
      #- POSTGRES_DB=amplizard
      #- POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: DockerfileDev  # If you have a separate Dockerfile, or omit if not needed
    ports: 
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# networks:
#   amplizard_net:
#     driver: bridge
